version: "3"
services: 
  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes: 
      - ./City.sql:/docker-entrypoint-initdb.d/City.sql
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
  app:
    build: ./
    ports: 
      - "80:80"


